
spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:auth_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


application:
  security:
    jwt:
      # Use a long, random string here (at least 256-bit for HS256)
      secret-key: ${JWT_SECRET_KEY}
      expiration: 3600000 # 1 hour in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days