spring.application.name=api-gateway
spring.config.import=optional:file:.env[.properties]

server.port=${APP_PORT:8085}

app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:5173}

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8080}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=wallet-service-wallets
spring.cloud.gateway.server.webmvc.routes[1].uri=${WALLET_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/wallets/**

spring.cloud.gateway.server.webmvc.routes[2].id=wallet-service-transactions
spring.cloud.gateway.server.webmvc.routes[2].uri=${WALLET_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/transactions/**

spring.cloud.gateway.server.webmvc.routes[3].id=transfer-service-transfers
spring.cloud.gateway.server.webmvc.routes[3].uri=${TRANSFER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/transfers/**

spring.cloud.gateway.server.webmvc.routes[4].id=transfer-service-exchange-rates
spring.cloud.gateway.server.webmvc.routes[4].uri=${TRANSFER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/exchange-rates/**

spring.cloud.gateway.server.webmvc.routes[5].id=ledger-service
spring.cloud.gateway.server.webmvc.routes[5].uri=${LEDGER_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/ledger/**
